<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>MetaWorld</title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css" integrity="sha512-NmLkDIU1C/C88wi324HBc+S2kLhi08PN5GDeUVVVC/BVt/9Izdsc9SVeVfA1UZbY3sHUlDSyRXhCzHfr6hmPPw==" crossorigin="anonymous" />

  <link rel="stylesheet" href="style.css">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flickity/2.2.1/flickity.min.css" integrity="sha512-ztsAq/T5Mif7onFaDEa5wsi2yyDn5ygdVwSSQ4iok5BPJQGYz1CoXWZSA7OgwGWrxrSrbF0K85PD5uLpimu4eQ==" crossorigin="anonymous" />

  <script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>


  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;700;900&display=swap" rel="stylesheet">

</head>
<body>
    <div class="header">
      
    
        <ul class="menu">
          
          <li><a href="">Info</a></li>
          <li><a href="">Cosa Fare</a></li>
          <li><a href="">Contatti</a></li>
          <li><a href="./registrazione.html">Registrati</a></li>
          <li><a href="">Coming Soon!</a></li>
        </ul>

        

          <div class="hamburger">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
      
        <div class="hero">
          <div class="hero__content reveal">
            <h1 class="big-text">MetaWorld</h1>
            

      
           
            <a href="./cercaparole.html" class="button">Benvenuto</a>

            <h2></h2>
            <h2 class="benvenuto">Benvenuto Nel Nostro Mondo Virtuale!</h2>
            <h2 class="benvenuto">Qui Puoi Trovare Tutto Quello Che</h2>
            <h2 class="benvenuto">Ti Serve!</h2>

             
          </div>


          



        </div>
            </div>
    <video autoplay muted loop id="video-back">
      <source src="https://player.vimeo.com/external/221185510.hd.mp4?s=2cda461950146045969fb307b661f63dc35a9d6c&profile_id=174" type="video/mp4">
    </video>
  </div>

      
      
      


      
</body>


          
</html>
  <!-- Jquery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/flickity/2.2.1/flickity.pkgd.min.js" integrity="sha512-Nx/M3T/fWprNarYOrnl+gfWZ25YlZtSNmhjHeC0+2gCtyAdDFXqaORJBj1dC427zt3z/HwkUpPX+cxzonjUgrA==" crossorigin="anonymous"></script>

  <script>
  $( document ).ready(function() {

    /* Open Panel */
    $( ".hamburger" ).on('click', function() {
      $(".menu").toggleClass("menu--open");
    });

  });


  ScrollReveal().reveal('.reveal',  { distance: '100px', duration: 1500, easing: 'cubic-bezier(.215, .61, .355, 1)', interval: 600 });

  ScrollReveal().reveal('.zoom',  { duration: 1500, easing: 'cubic-bezier(.215, .61, .355, 1)', interval: 200, scale: 0.65, mobile: false});



</script>


</body>
</html>
<style>
/* ! Base Style */

body{font-family: 'Inter', sans-serif;font-size: 16px; background-color: #f2e7e7; }

a{text-decoration: none;}

h1, h2, h3, h4, h5, p{color: rgb(0, 0, 0); padding-bottom: 30px;}

p{line-height: 28px; color:#666; font-weight: 300;}

.big-text{font-size: 70px;font-weight: 900; color: #000;}
.med-text{font-size: 40px;}
.normal-text{font-size: 20px;}
.small-text{font-size: 14px;}

.intro-text{text-transform: uppercase;font-size: 20px;font-weight: bold;}

.button{padding: 18px 28px; background:white; color:black; display: inline-block;border-radius: 4px; text-align: center;
  transition: 2.2s ease;
  -moz-transition: 2.2s ease;
  -webkit-transition: 2.0s ease;
  -o-transition: 2.2s ease;
  -ms-transform: 2.2s ease;}

  @import url(https://fonts.googleapis.com/css?family=Open+Sans);
 

/*ZOOM*/
/* Bottone Login animazione */
	.button:hover{
	transform : scale(1.05);
	-moz-transform : scale(1.05); /* Firefox */
	-webkit-transform : scale(1.05); /* Chrome - Safari */
	-o-transform : scale(1.05); /* Opera */
	-ms-transform : scale(1.05); /* IE */
	}
/* Game animazione */


@media (max-width: 768px) {

  .big-text{font-size: 40px;
  text-align: center;}
  .logo {
    margin-left: 10%;
  }

}



/* ! Header */

.header{
  width: 100%;
  position: fixed;
  z-index: 10;
  top:0;
  left:40%;
  transform: translateX(-50%);
  padding: 30px;
  display: flex;
  max-width: 1350px;
  
}

.logo{z-index: 1;
scale: 150%;
margin-left: 5%;
}

.menu{
  transition: all 1s cubic-bezier(.215, .61, .355, 1);
  width: 100%;
  z-index: 0;
  margin-left: 10%;
  margin-top: -1%;
  text-align: left;
}

.menu li{display: inline-block;}
.menu li a{color: #fff;padding: 15px;display: block;}

.hamburger{display: none;}

@media (max-width: 768px) {

  .cta{display: none;}

  .menu{position: absolute; top:0; right:-100%;background: #000;height: 100vh;padding-top: 80px;}
  .menu li{display: block;}
  .menu li a{padding: 15px 30px;font-size: 20px;}

  .menu--open{right:0%;}

  .hamburger{
    display: block;
    width: 30px;
    height: 30px;
    position: absolute;
    top:40px;
    right:30px
  }
  .hamburger span{background: #fff;height: 3px;width: 100%;display: block;margin-bottom: 5px;}

}

/* ! Hero */

.hero{
  position: relative;
  text-align: center;
  height: 100vh;
  display: flex; width: 100%;align-items: center;
  background: linear-gradient(0deg, rgba(255, 255, 255, 0.793), rgba(255, 255, 255, 0.793)),
   url('bg-video.png') no-repeat center center;
  background-size: cover;
  overflow: hidden;
}

.hero:after{
  content: ' ';
  width: 100%;
  height: 100%;
  display: block;
  position: absolute;
  top:0; left:0;
  background: #000;
  opacity: 0.4;
}

.hero__content{
  width: 100%;
  max-width: 1350px;
  margin: 0 auto;
  padding: 30px;
  z-index: 1;
  position: relative;
}

.hero__content h1,
.hero__content p{color: #fff;}

.hero--small{height: 450px;text-align: center;}


#video-back{
  position:absolute;
  bottom:0;
  left:0;
  min-width: 100%;
  min-height: 100%;
  z-index: 0;
}



/* ! Poster */

.poster{
  display: flex;
  height: 100vh;
  width: 100%;
  align-items: center;
}

.poster__img{width: 65%; height: 100%;}
.poster__img img{object-fit: cover; width: 100%;height: 100%;}
.poster__content{width: 35%;padding: 50px;}

@media (max-width: 768px) {
  .poster{flex-wrap: wrap;height: auto;}
  .poster__img,
  .poster__content{width: 100%;}
}

/* BG Cover */

.bg-cover{
  display: flex;
  padding: 100px 0;
  background: linear-gradient(0deg, rgba(0,0,0,.7), rgba(0,0,0, 0.7)),
   url('bg-video.png') no-repeat center center;
  background-size: cover;
}

.bg-cover__text{width: 50%;padding: 30px;}
.bg-cover__title{width: 50%;padding: 50px;display: flex;align-items: center;}

@media (max-width: 768px) {
  .bg-cover{flex-wrap: wrap; height: auto;}
  .bg-cover__text,
  .bg-cover__title{width: 100%;}
}


/* ! Grid */

.grid{display: flex; max-width: 1350px; padding: 0 30px;margin: 0 auto;}
.grid .col{width: 100%;}

@media (max-width: 768px) {
  .grid{flex-wrap: wrap}
}

/* ! Carousel */

.main-carousel{padding: 40px 0;}

.carousel-cell{
  height: 350px;
  width: 350px;
  margin-right: 40px;
}

.carousel-cell__content{
  width: 100%;
  height: 100%;
  background: #6adf91;
  border-radius: 100%;
  line-height: 350px;
  text-align: center;
}

/* Panel Blue */

.panel-blue{background: #4bb1e9;padding: 100px 30px;}
.panel-blue__text{display: flex;align-items: center;}
.dot{
  height: 250px;width: 250px;
  background: #6adf91;border-radius: 100%;
  line-height: 250px;
  text-align: center;
  display: inline-block;
  margin-right: 40px;
  margin-bottom: 40px;
}

/* Footer */

.footer{
  background: white;
  padding: 150px 0; 
}

/* ! Content */

.content{max-width: 900px; margin: 40px auto;}

.end{
}

.benvenuto{
  color: white;
  font-size: 20px;
  text-align: center;
  font-family: Verdana, Geneva, Tahoma, sans-serif;
}


